// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GallowRequest
	GallowReply
	Gallow
	GuessRequest
	GuessReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GallowRequest struct {
	Id         int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	RetryLimit int32 `protobuf:"varint,2,opt,name=RetryLimit" json:"RetryLimit,omitempty"`
}

func (m *GallowRequest) Reset()                    { *m = GallowRequest{} }
func (m *GallowRequest) String() string            { return proto.CompactTextString(m) }
func (*GallowRequest) ProtoMessage()               {}
func (*GallowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GallowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GallowRequest) GetRetryLimit() int32 {
	if m != nil {
		return m.RetryLimit
	}
	return 0
}

type GallowReply struct {
	Gallow []*Gallow `protobuf:"bytes,1,rep,name=Gallow" json:"Gallow,omitempty"`
}

func (m *GallowReply) Reset()                    { *m = GallowReply{} }
func (m *GallowReply) String() string            { return proto.CompactTextString(m) }
func (*GallowReply) ProtoMessage()               {}
func (*GallowReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GallowReply) GetGallow() []*Gallow {
	if m != nil {
		return m.Gallow
	}
	return nil
}

type Gallow struct {
	Id         int32           `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	RetryLimit int32           `protobuf:"varint,2,opt,name=RetryLimit" json:"RetryLimit,omitempty"`
	RetryLeft  int32           `protobuf:"varint,3,opt,name=RetryLeft" json:"RetryLeft,omitempty"`
	Word       string          `protobuf:"bytes,4,opt,name=Word" json:"Word,omitempty"`
	WordMasked string          `protobuf:"bytes,5,opt,name=WordMasked" json:"WordMasked,omitempty"`
	Guesses    []*GuessRequest `protobuf:"bytes,6,rep,name=Guesses" json:"Guesses,omitempty"`
}

func (m *Gallow) Reset()                    { *m = Gallow{} }
func (m *Gallow) String() string            { return proto.CompactTextString(m) }
func (*Gallow) ProtoMessage()               {}
func (*Gallow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Gallow) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gallow) GetRetryLimit() int32 {
	if m != nil {
		return m.RetryLimit
	}
	return 0
}

func (m *Gallow) GetRetryLeft() int32 {
	if m != nil {
		return m.RetryLeft
	}
	return 0
}

func (m *Gallow) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Gallow) GetWordMasked() string {
	if m != nil {
		return m.WordMasked
	}
	return ""
}

func (m *Gallow) GetGuesses() []*GuessRequest {
	if m != nil {
		return m.Guesses
	}
	return nil
}

type GuessRequest struct {
	GallowID int32  `protobuf:"varint,1,opt,name=GallowID" json:"GallowID,omitempty"`
	Letter   string `protobuf:"bytes,2,opt,name=Letter" json:"Letter,omitempty"`
}

func (m *GuessRequest) Reset()                    { *m = GuessRequest{} }
func (m *GuessRequest) String() string            { return proto.CompactTextString(m) }
func (*GuessRequest) ProtoMessage()               {}
func (*GuessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GuessRequest) GetGallowID() int32 {
	if m != nil {
		return m.GallowID
	}
	return 0
}

func (m *GuessRequest) GetLetter() string {
	if m != nil {
		return m.Letter
	}
	return ""
}

type GuessReply struct {
	Gallow         *Gallow `protobuf:"bytes,1,opt,name=Gallow" json:"Gallow,omitempty"`
	LetterPosition int32   `protobuf:"varint,4,opt,name=LetterPosition" json:"LetterPosition,omitempty"`
}

func (m *GuessReply) Reset()                    { *m = GuessReply{} }
func (m *GuessReply) String() string            { return proto.CompactTextString(m) }
func (*GuessReply) ProtoMessage()               {}
func (*GuessReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GuessReply) GetGallow() *Gallow {
	if m != nil {
		return m.Gallow
	}
	return nil
}

func (m *GuessReply) GetLetterPosition() int32 {
	if m != nil {
		return m.LetterPosition
	}
	return 0
}

func init() {
	proto.RegisterType((*GallowRequest)(nil), "GallowRequest")
	proto.RegisterType((*GallowReply)(nil), "GallowReply")
	proto.RegisterType((*Gallow)(nil), "Gallow")
	proto.RegisterType((*GuessRequest)(nil), "GuessRequest")
	proto.RegisterType((*GuessReply)(nil), "GuessReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hangman service

type HangmanClient interface {
	NewGallow(ctx context.Context, in *GallowRequest, opts ...grpc.CallOption) (*GallowReply, error)
	ListGallows(ctx context.Context, in *GallowRequest, opts ...grpc.CallOption) (*GallowReply, error)
	ResumeGallow(ctx context.Context, in *GallowRequest, opts ...grpc.CallOption) (*GallowReply, error)
	GuessLetter(ctx context.Context, in *GuessRequest, opts ...grpc.CallOption) (*GuessReply, error)
}

type hangmanClient struct {
	cc *grpc.ClientConn
}

func NewHangmanClient(cc *grpc.ClientConn) HangmanClient {
	return &hangmanClient{cc}
}

func (c *hangmanClient) NewGallow(ctx context.Context, in *GallowRequest, opts ...grpc.CallOption) (*GallowReply, error) {
	out := new(GallowReply)
	err := grpc.Invoke(ctx, "/Hangman/NewGallow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hangmanClient) ListGallows(ctx context.Context, in *GallowRequest, opts ...grpc.CallOption) (*GallowReply, error) {
	out := new(GallowReply)
	err := grpc.Invoke(ctx, "/Hangman/ListGallows", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hangmanClient) ResumeGallow(ctx context.Context, in *GallowRequest, opts ...grpc.CallOption) (*GallowReply, error) {
	out := new(GallowReply)
	err := grpc.Invoke(ctx, "/Hangman/ResumeGallow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hangmanClient) GuessLetter(ctx context.Context, in *GuessRequest, opts ...grpc.CallOption) (*GuessReply, error) {
	out := new(GuessReply)
	err := grpc.Invoke(ctx, "/Hangman/GuessLetter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hangman service

type HangmanServer interface {
	NewGallow(context.Context, *GallowRequest) (*GallowReply, error)
	ListGallows(context.Context, *GallowRequest) (*GallowReply, error)
	ResumeGallow(context.Context, *GallowRequest) (*GallowReply, error)
	GuessLetter(context.Context, *GuessRequest) (*GuessReply, error)
}

func RegisterHangmanServer(s *grpc.Server, srv HangmanServer) {
	s.RegisterService(&_Hangman_serviceDesc, srv)
}

func _Hangman_NewGallow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GallowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).NewGallow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/NewGallow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).NewGallow(ctx, req.(*GallowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hangman_ListGallows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GallowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).ListGallows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/ListGallows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).ListGallows(ctx, req.(*GallowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hangman_ResumeGallow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GallowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).ResumeGallow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/ResumeGallow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).ResumeGallow(ctx, req.(*GallowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hangman_GuessLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).GuessLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/GuessLetter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).GuessLetter(ctx, req.(*GuessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hangman_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hangman",
	HandlerType: (*HangmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGallow",
			Handler:    _Hangman_NewGallow_Handler,
		},
		{
			MethodName: "ListGallows",
			Handler:    _Hangman_ListGallows_Handler,
		},
		{
			MethodName: "ResumeGallow",
			Handler:    _Hangman_ResumeGallow_Handler,
		},
		{
			MethodName: "GuessLetter",
			Handler:    _Hangman_GuessLetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xed, 0xf4, 0x27, 0xfd, 0x72, 0xd3, 0x76, 0x71, 0x17, 0x1f, 0x43, 0x11, 0x2d, 0xb3, 0xd0,
	0x42, 0x71, 0x16, 0xf5, 0x01, 0x04, 0x11, 0x6a, 0xa1, 0x8a, 0x0c, 0x88, 0xeb, 0x48, 0xae, 0x12,
	0x6c, 0x9b, 0x9a, 0x99, 0x50, 0xfa, 0x5c, 0xbe, 0x81, 0x4f, 0x26, 0x9d, 0x99, 0xd8, 0xb4, 0x08,
	0xea, 0x2a, 0x39, 0xe7, 0x4c, 0x4e, 0xee, 0x39, 0x77, 0x20, 0x8c, 0x57, 0xa9, 0x5c, 0xe5, 0x99,
	0xc9, 0xc4, 0x25, 0x74, 0x27, 0xf1, 0x7c, 0x9e, 0xad, 0x15, 0xbd, 0x15, 0xa4, 0x0d, 0xf6, 0xa0,
	0x3e, 0x4d, 0x38, 0x1b, 0xb0, 0x61, 0x4b, 0xd5, 0xa7, 0x09, 0x1e, 0x03, 0x28, 0x32, 0xf9, 0x66,
	0x96, 0x2e, 0x52, 0xc3, 0xeb, 0x96, 0xaf, 0x30, 0x42, 0x42, 0x54, 0x1a, 0xac, 0xe6, 0x1b, 0x3c,
	0x81, 0xc0, 0x41, 0xce, 0x06, 0x8d, 0x61, 0x34, 0x6e, 0x4b, 0xaf, 0x7a, 0x5a, 0xbc, 0xb3, 0xf2,
	0xc4, 0x5f, 0x7f, 0x85, 0x47, 0x10, 0x3a, 0x44, 0xcf, 0x86, 0x37, 0xac, 0xbc, 0x23, 0x10, 0xa1,
	0xf9, 0x98, 0xe5, 0x09, 0x6f, 0x0e, 0xd8, 0x30, 0x54, 0xf6, 0x7d, 0xeb, 0xb8, 0x7d, 0xde, 0xc6,
	0xfa, 0x95, 0x12, 0xde, 0xb2, 0x4a, 0x85, 0xc1, 0x33, 0x68, 0x4f, 0x0a, 0xd2, 0x9a, 0x34, 0x0f,
	0xec, 0xb8, 0x5d, 0x69, 0xb1, 0x2f, 0x43, 0x95, 0xaa, 0xb8, 0x82, 0x4e, 0x55, 0xc0, 0x3e, 0xfc,
	0x73, 0x21, 0xa6, 0xd7, 0x3e, 0xc0, 0x17, 0xc6, 0xff, 0x10, 0xcc, 0xc8, 0x18, 0xca, 0x6d, 0x84,
	0x50, 0x79, 0x24, 0x1e, 0x00, 0xbc, 0xc7, 0x61, 0x51, 0xec, 0x9b, 0xa2, 0xf0, 0x14, 0x7a, 0xee,
	0xc3, 0xfb, 0x4c, 0xa7, 0x26, 0xcd, 0x96, 0x36, 0x59, 0x4b, 0x1d, 0xb0, 0xe3, 0x0f, 0x06, 0xed,
	0x9b, 0x78, 0xf9, 0xb2, 0x88, 0x97, 0x38, 0x82, 0xf0, 0x8e, 0xd6, 0x65, 0xbd, 0x72, 0x6f, 0xb3,
	0xfd, 0x8e, 0xac, 0x2c, 0x4a, 0xd4, 0xf0, 0x1c, 0xa2, 0x59, 0xaa, 0x8d, 0x23, 0xf5, 0x8f, 0xc7,
	0x25, 0x74, 0x14, 0xe9, 0x62, 0x41, 0xbf, 0xb4, 0x1f, 0x41, 0x64, 0xe3, 0xba, 0x71, 0x71, 0xbf,
	0xd9, 0x7e, 0x24, 0x77, 0x5d, 0x88, 0xda, 0x53, 0x60, 0x6f, 0xe3, 0xc5, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0xe6, 0x71, 0x14, 0x9a, 0x02, 0x00, 0x00,
}
