// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	HangmanRequest
	HangmanReply
	Gallow
	GuessRequest
	GuessReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HangmanRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *HangmanRequest) Reset()                    { *m = HangmanRequest{} }
func (m *HangmanRequest) String() string            { return proto.CompactTextString(m) }
func (*HangmanRequest) ProtoMessage()               {}
func (*HangmanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HangmanRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HangmanReply struct {
	Gallow []*Gallow `protobuf:"bytes,1,rep,name=gallow" json:"gallow,omitempty"`
}

func (m *HangmanReply) Reset()                    { *m = HangmanReply{} }
func (m *HangmanReply) String() string            { return proto.CompactTextString(m) }
func (*HangmanReply) ProtoMessage()               {}
func (*HangmanReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HangmanReply) GetGallow() []*Gallow {
	if m != nil {
		return m.Gallow
	}
	return nil
}

type Gallow struct {
	Id     int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status bool  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *Gallow) Reset()                    { *m = Gallow{} }
func (m *Gallow) String() string            { return proto.CompactTextString(m) }
func (*Gallow) ProtoMessage()               {}
func (*Gallow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Gallow) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gallow) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type GuessRequest struct {
	HangmanID int32  `protobuf:"varint,1,opt,name=hangmanID" json:"hangmanID,omitempty"`
	Letter    string `protobuf:"bytes,2,opt,name=letter" json:"letter,omitempty"`
}

func (m *GuessRequest) Reset()                    { *m = GuessRequest{} }
func (m *GuessRequest) String() string            { return proto.CompactTextString(m) }
func (*GuessRequest) ProtoMessage()               {}
func (*GuessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GuessRequest) GetHangmanID() int32 {
	if m != nil {
		return m.HangmanID
	}
	return 0
}

func (m *GuessRequest) GetLetter() string {
	if m != nil {
		return m.Letter
	}
	return ""
}

type GuessReply struct {
	LifeTotal      int32  `protobuf:"varint,1,opt,name=lifeTotal" json:"lifeTotal,omitempty"`
	LifeLeft       int32  `protobuf:"varint,2,opt,name=lifeLeft" json:"lifeLeft,omitempty"`
	Word           string `protobuf:"bytes,3,opt,name=word" json:"word,omitempty"`
	LetterPosition string `protobuf:"bytes,4,opt,name=letterPosition" json:"letterPosition,omitempty"`
}

func (m *GuessReply) Reset()                    { *m = GuessReply{} }
func (m *GuessReply) String() string            { return proto.CompactTextString(m) }
func (*GuessReply) ProtoMessage()               {}
func (*GuessReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GuessReply) GetLifeTotal() int32 {
	if m != nil {
		return m.LifeTotal
	}
	return 0
}

func (m *GuessReply) GetLifeLeft() int32 {
	if m != nil {
		return m.LifeLeft
	}
	return 0
}

func (m *GuessReply) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *GuessReply) GetLetterPosition() string {
	if m != nil {
		return m.LetterPosition
	}
	return ""
}

func init() {
	proto.RegisterType((*HangmanRequest)(nil), "HangmanRequest")
	proto.RegisterType((*HangmanReply)(nil), "HangmanReply")
	proto.RegisterType((*Gallow)(nil), "Gallow")
	proto.RegisterType((*GuessRequest)(nil), "GuessRequest")
	proto.RegisterType((*GuessReply)(nil), "GuessReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hangman service

type HangmanClient interface {
	NewGallow(ctx context.Context, in *HangmanRequest, opts ...grpc.CallOption) (*HangmanReply, error)
	ListGallows(ctx context.Context, in *HangmanRequest, opts ...grpc.CallOption) (*HangmanReply, error)
	ResumeGallow(ctx context.Context, in *HangmanRequest, opts ...grpc.CallOption) (*HangmanReply, error)
	GuessLetter(ctx context.Context, in *GuessRequest, opts ...grpc.CallOption) (*GuessReply, error)
}

type hangmanClient struct {
	cc *grpc.ClientConn
}

func NewHangmanClient(cc *grpc.ClientConn) HangmanClient {
	return &hangmanClient{cc}
}

func (c *hangmanClient) NewGallow(ctx context.Context, in *HangmanRequest, opts ...grpc.CallOption) (*HangmanReply, error) {
	out := new(HangmanReply)
	err := grpc.Invoke(ctx, "/Hangman/NewGallow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hangmanClient) ListGallows(ctx context.Context, in *HangmanRequest, opts ...grpc.CallOption) (*HangmanReply, error) {
	out := new(HangmanReply)
	err := grpc.Invoke(ctx, "/Hangman/ListGallows", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hangmanClient) ResumeGallow(ctx context.Context, in *HangmanRequest, opts ...grpc.CallOption) (*HangmanReply, error) {
	out := new(HangmanReply)
	err := grpc.Invoke(ctx, "/Hangman/ResumeGallow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hangmanClient) GuessLetter(ctx context.Context, in *GuessRequest, opts ...grpc.CallOption) (*GuessReply, error) {
	out := new(GuessReply)
	err := grpc.Invoke(ctx, "/Hangman/GuessLetter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hangman service

type HangmanServer interface {
	NewGallow(context.Context, *HangmanRequest) (*HangmanReply, error)
	ListGallows(context.Context, *HangmanRequest) (*HangmanReply, error)
	ResumeGallow(context.Context, *HangmanRequest) (*HangmanReply, error)
	GuessLetter(context.Context, *GuessRequest) (*GuessReply, error)
}

func RegisterHangmanServer(s *grpc.Server, srv HangmanServer) {
	s.RegisterService(&_Hangman_serviceDesc, srv)
}

func _Hangman_NewGallow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangmanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).NewGallow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/NewGallow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).NewGallow(ctx, req.(*HangmanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hangman_ListGallows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangmanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).ListGallows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/ListGallows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).ListGallows(ctx, req.(*HangmanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hangman_ResumeGallow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangmanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).ResumeGallow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/ResumeGallow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).ResumeGallow(ctx, req.(*HangmanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hangman_GuessLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HangmanServer).GuessLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hangman/GuessLetter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HangmanServer).GuessLetter(ctx, req.(*GuessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hangman_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hangman",
	HandlerType: (*HangmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGallow",
			Handler:    _Hangman_NewGallow_Handler,
		},
		{
			MethodName: "ListGallows",
			Handler:    _Hangman_ListGallows_Handler,
		},
		{
			MethodName: "ResumeGallow",
			Handler:    _Hangman_ResumeGallow_Handler,
		},
		{
			MethodName: "GuessLetter",
			Handler:    _Hangman_GuessLetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x6a, 0xc2, 0x30,
	0x14, 0xc6, 0x8d, 0x7f, 0xaa, 0x3d, 0x55, 0x07, 0xb9, 0x18, 0x45, 0x84, 0x95, 0x5c, 0x0c, 0x61,
	0x2c, 0x8a, 0x7b, 0x05, 0xc1, 0x0d, 0x64, 0x8c, 0xb0, 0x17, 0xc8, 0x30, 0xba, 0x40, 0x6c, 0xba,
	0x26, 0xa5, 0xec, 0x76, 0x4f, 0xb7, 0xc7, 0x1a, 0x4d, 0x63, 0x75, 0x5e, 0x79, 0xd7, 0xef, 0x6b,
	0xf2, 0x3b, 0x87, 0x1f, 0x81, 0x90, 0x67, 0x92, 0x66, 0xb9, 0xb6, 0x9a, 0x24, 0x30, 0x7e, 0xe6,
	0xe9, 0xfe, 0xc0, 0x53, 0x26, 0xbe, 0x0a, 0x61, 0x2c, 0x1e, 0x43, 0x5b, 0x6e, 0x63, 0x94, 0xa0,
	0x59, 0x8f, 0xb5, 0xe5, 0x96, 0xcc, 0x61, 0xd8, 0x9c, 0xc8, 0xd4, 0x37, 0xbe, 0x83, 0x60, 0xcf,
	0x95, 0xd2, 0x65, 0x8c, 0x92, 0xce, 0x2c, 0x5a, 0xf6, 0xe9, 0xda, 0x45, 0xe6, 0x6b, 0xb2, 0x80,
	0xa0, 0x6e, 0x2e, 0x51, 0xf8, 0x16, 0x02, 0x63, 0xb9, 0x2d, 0x4c, 0xdc, 0x4e, 0xd0, 0x6c, 0xc0,
	0x7c, 0x22, 0x2b, 0x18, 0xae, 0x0b, 0x61, 0xcc, 0x71, 0x85, 0x29, 0x84, 0x9f, 0xf5, 0xc8, 0x97,
	0x95, 0xbf, 0x7e, 0x2a, 0x2a, 0x8a, 0x12, 0xd6, 0x8a, 0xdc, 0x51, 0x42, 0xe6, 0x13, 0xf9, 0x41,
	0x00, 0x1e, 0x53, 0xed, 0x39, 0x85, 0x50, 0xc9, 0x9d, 0x78, 0xd7, 0x96, 0xab, 0x23, 0xa4, 0x29,
	0xf0, 0x04, 0x06, 0x55, 0xd8, 0x88, 0x9d, 0x75, 0x98, 0x1e, 0x6b, 0x32, 0xc6, 0xd0, 0x2d, 0x75,
	0xbe, 0x8d, 0x3b, 0x0e, 0xef, 0xbe, 0xf1, 0x3d, 0x8c, 0xeb, 0x31, 0x6f, 0xda, 0x48, 0x2b, 0x75,
	0x1a, 0x77, 0xdd, 0xdf, 0x8b, 0x76, 0xf9, 0x8b, 0xa0, 0xef, 0x75, 0xe1, 0x47, 0x08, 0x5f, 0x45,
	0xe9, 0x5d, 0xdc, 0xd0, 0xff, 0x9e, 0x27, 0x23, 0x7a, 0xae, 0x95, 0xb4, 0xf0, 0x1c, 0xa2, 0x8d,
	0x34, 0xb6, 0x3e, 0x6f, 0xae, 0xb8, 0xb0, 0x80, 0x21, 0x13, 0xa6, 0x38, 0x88, 0xab, 0x47, 0x3c,
	0x40, 0xe4, 0x0c, 0x6d, 0xdc, 0xd2, 0x78, 0x44, 0xcf, 0xb5, 0x4f, 0x22, 0x7a, 0xd2, 0x47, 0x5a,
	0x1f, 0x81, 0x7b, 0x21, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xb3, 0xac, 0xa2, 0x2e,
	0x02, 0x00, 0x00,
}
